# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  TrunkDir: "{{.ROOT_DIR}}/.trunk"
  TrunkConfigDir: "{{.TrunkDir}}/configs"

includes:
  workstation:
    aliases: [ws]
    taskfile: .taskfiles/workstation/Taskfile.yaml
  trunk:
    aliases: [tr]
    taskfile: .taskfiles/trunk/Taskfile.yaml
  go:
    aliases: [g]
    taskfile: .taskfiles/go/Taskfile.yaml
  docs:
    aliases: [docusaurus, d, wiki]
    taskfile: .taskfiles/docs/Taskfile.yaml

tasks:
  default:
    cmd: task -l
    silent: true
